import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { RegisterDocumentDto, ListDocumentsQueryDto, PresignUploadDto } from './dto/document.dto';
import { S3Util } from '../../common/utils/s3.util';

@Injectable()
export class DocumentsService {
  constructor(private prisma: PrismaService) {}

  /** Step 1 of the upload flow: get a presigned S3 PUT URL. The browser PUTs the file directly to S3, then calls register() with the returned fileUrl. */
  getUploadUrl(dto: PresignUploadDto) {
    return S3Util.createPresignedUpload(dto.fileName, dto.mimeType);
  }

  /**
   * Records metadata for a file already uploaded to S3 via a presigned URL
   * (generated by a not-yet-built `/documents/upload-url` endpoint in the
   * AWS Deployment phase). Keeping upload and registration separate avoids
   * routing large binaries through this API server.
   */
  async register(organizationId: string, dto: RegisterDocumentDto, uploadedById?: string) {
    if (dto.farmerId) {
      const farmer = await this.prisma.farmer.findFirst({ where: { id: dto.farmerId, organizationId } });
      if (!farmer) throw new NotFoundException('Farmer not found');
    }
    return this.prisma.document.create({
      data: {
        organizationId,
        type: dto.type,
        fileUrl: dto.fileUrl,
        fileName: dto.fileName,
        mimeType: dto.mimeType,
        farmer: dto.farmerId ? { connect: { id: dto.farmerId } } : undefined,
        entityType: dto.entityType,
        entityId: dto.entityId,
        uploadedById,
      },
    });
  }

  async getById(id: string, organizationId: string) {
    const doc = await this.prisma.document.findFirst({ where: { id, organizationId } });
    if (!doc) throw new NotFoundException('Document not found');
    return doc;
  }

  list(organizationId: string, query: ListDocumentsQueryDto) {
    const page = Math.max(1, Number(query.page) || 1);
    const limit = Math.min(100, Math.max(1, Number(query.limit) || 20));
    const where = {
      organizationId,
      ...(query.farmerId ? { farmerId: query.farmerId } : {}),
      ...(query.entityType ? { entityType: query.entityType } : {}),
      ...(query.entityId ? { entityId: query.entityId } : {}),
      ...(query.type ? { type: query.type } : {}),
    };

    return Promise.all([
      this.prisma.document.findMany({
        where,
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      this.prisma.document.count({ where }),
    ]).then(([items, total]) => ({ items, meta: { page, limit, total } }));
  }
}
